---
# Source: btp-cf-env-runtime/charts/crossplane-provider-sap-btp-account/templates/mcp/btp-subscriptions/servicemanager.yaml
apiVersion: account.btp.sap.crossplane.io/v1beta1
kind: ServiceManager
metadata:
  name: subaccount1
  labels:
    openmcp.cloud/blueprint-building-block: "crossplane-provider-sap-btp-account"
    openmcp.cloud/blueprint-building-block-version: "0.0.13"
spec:
  writeConnectionSecretToRef:
    name: btp-service-manager-btp-account-provider-config-subaccount1
    namespace: default
  forProvider:
    subaccountRef:
      name: subaccount1
  providerConfigRef:
    name: "btp-account-provider-config"
